# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16193040b1296eb50b37777853a81b6bd6233abe1e87e6e501b12e054bd0f7d1868de4789df4de65432abf52a3a8be7e1ad185e30698f0280c148b5e61dd9fe6

test:
  secret_key_base: c711d9b8793373fae56b9142c66191b92ff6b08ffd6978b6afef2b8243332c6e3f7e5c1cc780130cf381723f95a5f5c6a7ba364631c66247da49a660a92e71df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
